if (self.CavalryLogger) { CavalryLogger.start_js(["5BDuT"]); }

__d("LinkReactUnsafeHrefTypedLogger",["Banzai","GeneratedLoggerUtils","nullthrows"],(function a(b,c,d,e,f,g){"use strict";__p&&__p();function h(){this.clear()}h.prototype.log=function(){c("GeneratedLoggerUtils").log("logger:LinkReactUnsafeHrefLoggerConfig",this.$LinkReactUnsafeHrefTypedLogger1,c("Banzai").BASIC)};h.prototype.logVital=function(){c("GeneratedLoggerUtils").log("logger:LinkReactUnsafeHrefLoggerConfig",this.$LinkReactUnsafeHrefTypedLogger1,c("Banzai").VITAL)};h.prototype.clear=function(){this.$LinkReactUnsafeHrefTypedLogger1={};return this};h.prototype.updateData=function(j){this.$LinkReactUnsafeHrefTypedLogger1=babelHelpers["extends"]({},this.$LinkReactUnsafeHrefTypedLogger1,j);return this};h.prototype.setDocumentLocation=function(j){this.$LinkReactUnsafeHrefTypedLogger1.document_location=j;return this};h.prototype.setHref=function(j){this.$LinkReactUnsafeHrefTypedLogger1.href=j;return this};var i={document_location:true,href:true};f.exports=h}),null);
__d("isSecureInstagramDotComURI",[],(function a(b,c,d,e,f,g){var h=new RegExp("(^|\\.)instagram\\.com$","i"),i=["https"];function j(k){return i.includes(k.getProtocol())&&h.test(k.getDomain())}f.exports=j}),null);
__d("isWitDotAiURI",[],(function a(b,c,d,e,f,g){var h=new RegExp("(^|\\.)wit\\.ai$","i"),i=["https"];function j(k){if(k.isEmpty()&&k.toString()!=="#")return false;if(!k.getDomain()&&!k.getProtocol())return true;return i.indexOf(k.getProtocol())!==-1&&h.test(k.getDomain())}f.exports=j}),null);
__d("LinkHrefChecker",["ErrorUtils","LinkReactUnsafeHrefTypedLogger","URI","ex","isSecureInstagramDotComURI","isFacebookURI","isMessengerDotComURI","isBonfireURI","isWitDotAiURI"],(function a(b,c,d,e,f,g){__p&&__p();function h(n){return n.startsWith("#")||n.startsWith("/")&&!n.startsWith("//")}function i(n){return n.startsWith("mailto:")}function j(n,o){if(h(n)||i(n))return true;var p=l(n),q=p?p.getProtocol():"";return q===o||q===""||q==="http"||q==="https"}function k(n){if(h(n))return true;var o=l(n);return o==null||c("isFacebookURI")(o)||c("isMessengerDotComURI")(o)||c("isBonfireURI")(o)||c("isSecureInstagramDotComURI")(o)||c("isWitDotAiURI")(o)}function l(n){try{return new(c("URI"))(n)}catch(o){return null}}var m={logIfInvalidProtocol:function n(o,p){if(!j(o,p))new(c("LinkReactUnsafeHrefTypedLogger"))().setHref(o).setDocumentLocation(document.location.toString()).log()}};f.exports=m}),null);
__d("SRTUtils",["DateConsts"],(function a(b,c,d,e,f,g){var h=c("DateConsts").SEC_PER_MIN,i=c("DateConsts").SEC_PER_HOUR,j={convertSecondsToString:function k(l){var m=Math.floor(l/i),n=Math.floor(l%i/h),o=Math.ceil(l%i%h),p=m.toString().length;p=p>1?p:2;return("0"+m).slice(-p)+":"+("0"+n).slice(-2)+":"+("0"+o).slice(-2)},convertSecondsToMinutes:function k(l){return Math.floor(l/h)},convertMinutesToSeconds:function k(l){return l*h}};f.exports=j}),null);
__d("compose",[],(function a(b,c,d,e,f,g){function h(){for(var i=arguments.length,j=Array(i),k=0;k<i;k++)j[k]=arguments[k];if(j.length<2)throw new Error("Compose expects two or more functions as arguments.");var l=j.reverse(),m=l[0],n=l[1],o=l.slice(2),p=function q(){return n(m.apply(undefined,arguments))};return o.length===0?p:h.apply(undefined,[p].concat(o).reverse())}f.exports=h}),null);
__d("FbtLoggerImpl",["BanzaiLogger","ScriptPath"],(function a(b,c,d,e,f,g){var h={logImpression:function i(j){c("BanzaiLogger").log("FbtImpressionsLoggerConfig",{hash:j,sample_rate:100,script_path:c("ScriptPath").getScriptPath()})}};f.exports=h}),null);
__d("XAtWorkSAMLUnlinkController",["XController"],(function a(b,c,d,e,f,g){f.exports=c("XController").create("/work/saml/unlink_account/",{})}),null);
__d("XPresenceReconnectAsyncController",["XController"],(function a(b,c,d,e,f,g){f.exports=c("XController").create("/ajax/presence/reconnect.php",{reason:{type:"Int"}})}),null);